import { emptyExperiment, migrate } from './core/schema.js';
import { createStore } from './core/store.js';
import { createRouter } from './core/router.js';
import { renderShell } from './ui/shell.js';
import { clearAll, listSaved, loadExperiment, saveExperiment } from './core/persist.js';
import { shapeAppKb } from './engine/kbpack.js';
import { namingStep } from './ui/steps/naming.js';
import { createDescribeStep } from './ui/steps/describe.js';
import { designStep } from './ui/steps/design.js';

const AUTOSAVE_DEBOUNCE_MS = 500;

/**
 * Read the knowledge pack from the ONE place its global is read, then hand
 * it to shapeAppKb (engine/kbpack.js) for the actual shaping -- that part is
 * a pure function and is what's under test; this wrapper is the one line
 * that is allowed to touch globalThis.
 *
 * globalThis.__MICRONAUT_KB__ is embedded by tools/build_single_file.py
 * (release) or web/kb.dev.js (dev, generated by tools/export_markers_kb.py)
 * -- both aggregate web/kb/*.json by filename stem. TOTAL: an absent/
 * malformed KB degrades to "no markers known, no questions, no advice"
 * (surfaced via the shell's toast), never a white screen.
 */
function loadAppKb() {
  const rawKb = typeof globalThis !== 'undefined' ? globalThis.__MICRONAUT_KB__ : undefined;
  return shapeAppKb(rawKb);
}

function loadInitialExperiment() {
  const saved = listSaved();
  if (saved.length > 0) {
    const raw = loadExperiment(saved[0]);
    if (raw) {
      try {
        // Runs the C0-1 schema-version guard on the actual load path, not
        // just in its own unit tests -- otherwise a future schema bump
        // would be silently misread as the current version instead of
        // raising the clear error migrate() exists to give.
        return migrate(raw);
      } catch (err) {
        console.error('Discarding an unreadable autosave, starting fresh:', err);
      }
    }
  }
  return emptyExperiment();
}

// Bootstrap, not top-level await -- the single-file inliner forbids
// top-level await since the released artifact is one classic (non-module,
// non-async) IIFE.
function init() {
  const initialExperiment = loadInitialExperiment();
  const store = createStore(initialExperiment);

  const kb = loadAppKb();
  const describeStep = createDescribeStep(kb);
  const steps = [describeStep, designStep, namingStep];
  const router = createRouter(steps);

  const root = document.getElementById('app');
  const { main, showToast } = renderShell(root, store, router, {
    // Clear persisted state BEFORE reloading. Resetting the in-memory store
    // instead would immediately trip the autosave subscription below and write
    // the empty experiment back as a NEW ring entry, leaving the old slots in
    // place for listSaved() to resurrect on the next load.
    onReset: () => {
      clearAll();
      window.location.reload();
    },
  });

  if (kb.issues.length > 0) {
    showToast(
      `Knowledge pack loaded with ${kb.issues.length} issue(s) -- some markers or guidance may be unavailable.`
    );
  }

  function renderActiveStep(id) {
    const step = steps.find((s) => s.id === id) || steps[0];
    step.render(main, store, { showToast, advisor: kb.advisor });
  }

  router.onChange(renderActiveStep);
  renderActiveStep(router.current());

  // Debounced: saving on every keystroke would fill the 5-slot ring buffer
  // with near-duplicate snapshots of the last few characters typed, rather
  // than the last 5 genuinely distinct states the ring buffer exists to
  // preserve as history.
  let saveTimer = null;
  store.subscribe(() => {
    if (saveTimer) window.clearTimeout(saveTimer);
    saveTimer = window.setTimeout(() => {
      saveExperiment(store.get(), {
        onQuotaExceeded: () => {
          showToast('Storage is full -- changes are not being saved automatically. Export to a file.');
        },
      });
    }, AUTOSAVE_DEBOUNCE_MS);
  });
}

init();
