import { createDefaultStudy } from './core/defaultStudy.js';
import { emptyExperiment } from './core/schema.js';
import { createStore } from './core/store.js';
import { createRouter } from './core/router.js';
import { renderShell } from './ui/shell.js';
import { clearAll, loadMostRecentRecoverable, saveExperiment, takeStashedDraft } from './core/persist.js';
import { shapeAppKb } from './engine/kbpack.js';
import { createNamingStep } from './ui/steps/naming.js';
import { createDescribeStep } from './ui/steps/describe.js';
import { designStep } from './ui/steps/design.js';
import { studyStep } from './ui/steps/study.js';
import { createPanelStep } from './ui/steps/panel.js';
import { createOverviewStep } from './ui/steps/overview.js';
import { guideStep } from './ui/steps/guide.js';
import { homeStep, loadWalkthroughSeen, saveWalkthroughSeen } from './ui/steps/home.js';

const AUTOSAVE_DEBOUNCE_MS = 500;

/**
 * Read the knowledge pack from the ONE place its global is read, then hand
 * it to shapeAppKb (engine/kbpack.js) for the actual shaping -- that part is
 * a pure function and is what's under test; this wrapper is the one line
 * that is allowed to touch globalThis.
 *
 * globalThis.__MICRONAUT_KB__ is embedded by tools/build_single_file.py
 * (release) or web/kb.dev.js (dev, generated by tools/export_markers_kb.py)
 * -- both aggregate web/kb/*.json by filename stem. TOTAL: an absent/
 * malformed KB degrades to "no markers known, no questions, no advice"
 * (surfaced via the shell's toast), never a white screen.
 */
function loadAppKb() {
  const rawKb = typeof globalThis !== 'undefined' ? globalThis.__MICRONAUT_KB__ : undefined;
  return shapeAppKb(rawKb);
}

/**
 * The thin wrapper around core/persist.js's loadMostRecentRecoverable that
 * supplies main.js's own console.error logging and the createDefaultStudy()
 * fallback -- persist.js deliberately doesn't know what a fresh study looks
 * like, so `experiment: null` means "start fresh" here. Only fires when
 * NO usable autosave exists at all (true first run, or every ring slot was
 * corrupted) -- an existing in-progress study is never touched.
 */
function loadInitialExperiment() {
  // A model-drafted study opened in a new tab (core/draft.js) wins over the
  // autosave, and is consumed one-shot so a later reload of THIS tab falls
  // back to the normal autosave path rather than re-opening the draft
  // forever. Deliberately ahead of loadMostRecentRecoverable: the draft was
  // stashed by the other tab moments ago and is the reason this tab exists.
  const draft = takeStashedDraft();
  if (draft) {
    return { experiment: draft, skippedCount: 0, totalSaved: 0, isDraft: true };
  }
  const { experiment, skippedCount, totalSaved } = loadMostRecentRecoverable({
    onUnreadable: (id, err) =>
      console.error(`Discarding an unreadable autosave (slot ${id}), trying the next one:`, err),
  });
  return { experiment: experiment || createDefaultStudy(), skippedCount, totalSaved, isDraft: false };
}

// Bootstrap, not top-level await -- the single-file inliner forbids
// top-level await since the released artifact is one classic (non-module,
// non-async) IIFE.
function init() {
  const { experiment: initialExperiment, skippedCount, totalSaved, isDraft } = loadInitialExperiment();
  const store = createStore(initialExperiment);

  const kb = loadAppKb();
  const describeStep = createDescribeStep(kb);
  const panelStep = createPanelStep(kb);
  const overviewStep = createOverviewStep(kb);
  const namingStep = createNamingStep(kb);
  // Home FIRST (zen-planner Phase 1's reframe): the router lands on
  // steps[0] by default, and Home is now the deliberate landing page --
  // superseding Study's earlier claim to that spot (see the walkthrough
  // redirect below main.js's step nav order also carries the reframe's
  // "question before microscope" story: Describe ("Project") moves ahead of
  // Study/Design so the project-level questioning happens before the study
  // axes and the microscopy details, and Naming/Overview close out as
  // Outputs.
  // Panel ("Microscopy"): it reads naming.fields.markers (Naming is where
  // that field is entered) plus its own phase-scoped acquisition interview.
  // See ui/steps/panel.js's module header and
  // docs/plans/planner-web-color-panel.md, Decision 1.
  // Overview last: it is a pure READ over every other step's data (the
  // shareable diagram + deterministic walkthrough), never a place new facts
  // are entered -- see ui/steps/overview.js's module header.
  // Guide LAST: stays permanently in the nav so it is always reachable, even
  // though Home's own "Take the walkthrough" card is now the more prominent
  // entry point to the same content. See ui/steps/guide.js's header.
  const steps = [homeStep, describeStep, studyStep, designStep, panelStep, namingStep, overviewStep, guideStep];
  const router = createRouter(steps);

  // First-visit walkthrough default (zen-planner Phase 1): a genuinely new
  // session -- totalSaved === 0, meaning loadMostRecentRecoverable found NO
  // prior autosave for this browser at all, the same signal loadInitialExperiment
  // already computed above -- lands on the Guide step's walkthrough content
  // instead of Home, once, before this tab's first paint. Marked seen
  // immediately so a reload of the SAME session does not repeat the
  // redirect (the seeded oregano example is not "no prior session" the
  // second time around) -- see ui/steps/home.js's "Don't show again" control
  // for the same flag, set explicitly instead of implicitly.
  //
  // !isDraft matters here: loadInitialExperiment's draft branch above
  // hardcodes totalSaved: 0 UNCONDITIONALLY (it returns before ever calling
  // loadMostRecentRecoverable) -- without this guard, an experienced user
  // who just used "Draft a study from this" in another tab would get
  // redirected away from their freshly-drafted study on this new tab, which
  // is the opposite of a first-time visitor.
  if (totalSaved === 0 && !isDraft && !loadWalkthroughSeen()) {
    saveWalkthroughSeen();
    router.navigate('guide');
  }

  const root = document.getElementById('app');
  const { main, showToast } = renderShell(root, store, router, {
    kbIssueCount: kb.issues.length,
    // Clear persisted state BEFORE reloading. Resetting the in-memory store
    // instead would immediately trip the autosave subscription below and write
    // the empty experiment back as a NEW ring entry, leaving the old slots in
    // place for listSaved() to resurrect on the next load.
    onReset: () => {
      clearAll();
      window.location.reload();
    },
    // "New study": start from a genuinely blank experiment, not the oregano
    // example. Clear the autosave ring, persist the blank as the newest entry
    // so the reload restores IT (loadInitialExperiment would otherwise fall
    // straight back to createDefaultStudy when it finds no save), then reload
    // through the same clean path onReset uses.
    onNewBlank: () => {
      clearAll();
      saveExperiment(emptyExperiment());
      window.location.reload();
    },
  });

  if (kb.issues.length > 0) {
    showToast(
      `Knowledge pack loaded with ${kb.issues.length} issue(s) -- some markers or guidance may be unavailable.`
    );
  }

  // Shown AFTER the KB toast (shell.js's showToast is a single status
  // element, not a queue -- the later call wins the visible window), since
  // a possible-data-loss message is rarer and more consequential than a
  // KB-content issue.
  if (skippedCount > 0) {
    showToast(
      skippedCount < totalSaved
        ? `Recovered your work -- skipped ${skippedCount} unreadable autosave(s) and used an older one instead.`
        : `Couldn't read any of your ${totalSaved} saved experiment(s) -- starting fresh. Nothing was deleted.`
    );
  }

  // Last, so it wins the single visible toast slot: a user who just landed
  // in a drafted study most needs to know that nothing here is confirmed.
  if (isDraft) {
    showToast('This is a model-drafted study -- every value is a suggestion awaiting your review.');
  }

  function renderActiveStep(id) {
    const step = steps.find((s) => s.id === id) || steps[0];
    step.render(main, store, { showToast, advisor: kb.advisor, router });
  }

  router.onChange(renderActiveStep);
  renderActiveStep(router.current());

  // Every step's render() caches activeAssayId ONCE and documents that this
  // is only safe because the active assay never changes for the lifetime of
  // one render (see e.g. design.js's identical comment). The assay switcher
  // (shell.js) now makes that untrue, so switching assays must force a full
  // re-render of whichever step is on screen -- same as a route change,
  // because every closure inside render() (currentDesign(), prefill, etc.)
  // was built from the OLD assayId. Guarded on an actual change so ordinary
  // per-keystroke field edits (which also flow through this same
  // store.subscribe channel via the autosave one below) never trigger it.
  //
  // ALSO re-render when `assays` itself is a new array reference -- not just
  // when activeAssayId changes. Deleting a NON-active assay via the
  // switcher's "x" (shell.js's renderSwitcher) calls store.patch(result),
  // which replaces `assays` but leaves activeAssayId untouched, so the
  // activeAssayId check alone never fires; a step that lists every assay by
  // reading store.get().assays directly (study.js) then keeps showing the
  // deleted assay until some UNRELATED action happens to change
  // activeAssayId too. This is a real bug that shipped: verified live --
  // the switcher pill disappeared correctly (it has its own subscription)
  // while the Study step's own assay list kept a stale row for the assay
  // just removed. Safe as a reference check, not a deep one: core/store.js's
  // setPath MUTATES nested state in place (core/paths.js), so `assays` keeps
  // the SAME reference across ordinary per-keystroke field edits and only
  // gets a new one when store.patch() explicitly replaces it (add/remove
  // assay) -- this can never fire on a keystroke.
  let lastActiveAssayId = store.get().activeAssayId;
  let lastAssays = store.get().assays;
  store.subscribe((state) => {
    if (state.activeAssayId !== lastActiveAssayId || state.assays !== lastAssays) {
      lastActiveAssayId = state.activeAssayId;
      lastAssays = state.assays;
      renderActiveStep(router.current());
    }
  });

  // Debounced: saving on every keystroke would fill the 5-slot ring buffer
  // with near-duplicate snapshots of the last few characters typed, rather
  // than the last 5 genuinely distinct states the ring buffer exists to
  // preserve as history.
  let saveTimer = null;
  store.subscribe(() => {
    if (saveTimer) window.clearTimeout(saveTimer);
    saveTimer = window.setTimeout(() => {
      saveExperiment(store.get(), {
        onQuotaExceeded: () => {
          showToast('Storage is full -- changes are not being saved automatically. Export to a file.');
        },
      });
    }, AUTOSAVE_DEBOUNCE_MS);
  });
}

init();
